### ISSUE TITLE
Bug when sequences are smaller than max_seq

### ISSUE THREAD

**Issue by ccolas** [gwinndr/MusicTransformer-Pytorch#15]
Hi!
Small bug to correct, line 92 of the e_piano.py file:

`tgt[raw_len]        = TOKEN_END` throws an error because raw_len is out of bounds. This should be `raw_len-1`. This is not a problem with the maestro dataset, which probably contains more than max_seq=2048 events for all performances, but this can show up in custom datasets.

**Comment by gwinndr** [comment]
Thanks for letting me know! I'll take a look.

**Comment by gwinndr** [comment]
Fixed, my apologies
