### ISSUE TITLE
pre-trained version?

### ISSUE THREAD

**Issue by johncwok** [gwinndr/MusicTransformer-Pytorch#16]
Hi! Is there a way to access the weights to get a pre-trained version of the network? I have searched the repo but couldn't find anything, and I cannot train such a network on my small laptop.

**Comment by gwinndr** [comment]
I do have some results here:
https://drive.google.com/drive/folders/1vSqfP_ami74VV9Pe-oKYVCN9gTuoggCg?usp=sharing

When I get more time, I was planning on getting some fully trained versions. For now, the colab should suffice (which I suspect you already used :) )
