### ISSUE TITLE
Thank you very much :)

### ISSUE THREAD

**Issue by asigalov61** [gwinndr/MusicTransformer-Pytorch#9]
Hey Damon,

I just wanted to say hi and thank you for your fantastic work on Music Transformer PyTorch repo/code.

It works great and I was able to reproduce the results.

I have created a nice Google Colab with your repo/code, so I wanted to invite you to check it out. And if you like, feel free to add it to your repo so that people can try it easily and quickly.

https://github.com/asigalov61/SuperPiano/blob/master/Super_Piano_3.ipynb

Sincerely,

Alex

**Comment by gwinndr** [comment]
Hi Alex,

Glad to hear the results were reproducible. Even happier to hear that you had as much fun with this as I did :-)

Your Colab looks amazing and is extremely friendly to use. I went ahead and added a link to it at the top of the README so others can hopefully see and use it. Let me know if you need any help with anything.

Again, awesome work 👍 
Damon

**Comment by asigalov61** [comment]
Of'course, Damon! I am one the few old-schoolers that still care and believe in the power of open-source, sharing, and just having fun with computers (and in this case - music).

Thank you very much for adding my link and liking my colab. It means a lot to me :)

Most sincerely from always sunny Los Angeles,

Alex
